# Generated by Django 3.2.5 on 2021-09-11 10:55

from django.db import migrations, models
import kitchen_shop.api.journal.logic.post_image_filepath
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('preview_text', models.TextField()),
                ('main_text', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, upload_to=kitchen_shop.api.journal.logic.post_image_filepath.post_image_path)),
            ],
        ),
    ]
